spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/interviewdb
    username: postgres
    password: postgres

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  ai:
    ollama:
      base-url: http://localhost:11434
      chat:
        model: llama3
      embedding:
        model: nomic-embed-text

    vectorstore:
      pgvector:
        initialize-schema: true

jwt:
  secret: mySuperSecretKeyForJwtAuthentication
